language: node_js
node_js:
  - "10"
script:
  - yarn run build
deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
  project: ./build/
  on:
    tags: true
    branch: master