language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: test
      script: yarn run test
    - stage: build
      script: yarn run build
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
    