language: node_js
node_js:
  - "10"
install:
  - yarn install --ignore-engines
cache: yarn
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
      script: yarn run test
    - stage: deploy
      script: yarn run build
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: master
        script:
          - yarn run semantic-release
